// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoFullStack1.Models;

#nullable disable

namespace ProjetoFullStack1.Migrations
{
    [DbContext(typeof(projetoGuriContext))]
    partial class projetoGuriContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjetoFullStack1.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAluno"), 1L, 1);

                    b.Property<int>("CodTurma")
                        .HasColumnType("int")
                        .HasColumnName("codTurma");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("dataInicio");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("date")
                        .HasColumnName("dataNasc");

                    b.Property<int>("Frequencia")
                        .HasColumnType("int")
                        .HasColumnName("frequencia");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nomeAluno");

                    b.Property<string>("NomeResponsavel1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nomeResponsavel1");

                    b.Property<string>("NomeResponsavel2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nomeResponsavel2");

                    b.Property<int>("TelContato")
                        .HasColumnType("int")
                        .HasColumnName("telContato");

                    b.HasKey("IdAluno")
                        .HasName("PK__alunos__8092FCB384CA9662");

                    b.HasIndex("CodTurma");

                    b.ToTable("alunos", (string)null);
                });

            modelBuilder.Entity("ProjetoFullStack1.Models.Turma", b =>
                {
                    b.Property<int>("CodTurma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codTurma");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTurma"), 1L, 1);

                    b.Property<string>("Instrumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("instrumento");

                    b.Property<string>("ProfResponsavel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("profResponsavel");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("turno");

                    b.HasKey("CodTurma")
                        .HasName("PK__turmas__8EE1EC2F224B1FD3");

                    b.ToTable("turmas", (string)null);
                });

            modelBuilder.Entity("ProjetoFullStack1.Models.Aluno", b =>
                {
                    b.HasOne("ProjetoFullStack1.Models.Turma", "CodTurmaNavigation")
                        .WithMany("Alunos")
                        .HasForeignKey("CodTurma")
                        .IsRequired()
                        .HasConstraintName("FK__alunos__codTurma__398D8EEE");

                    b.Navigation("CodTurmaNavigation");
                });

            modelBuilder.Entity("ProjetoFullStack1.Models.Turma", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
